- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
    # installing Nginx


- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes
  
- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent