- name: Play 1
  hosts: all
  vars:
    - URL: websitenew
      
  tasks:
    - name: Copy a "sudoers" file on the remote machine for editing
      ansible.builtin.copy:
        src:  temp.xml
        dest: /home/centos

    - name: Run shell command
      shell: uptime
      register: OUT

    - name: Print Message
      ansible.builtin.debug:
       msg: Hellow to all from play1 task1 {{URL}} {{ OUT.stdout }}