- name: Play 1
  hosts: all
  vars:
    - URL: websitenew
      
  tasks:
    - name: Hellow to all from play1
      shell: uptime
      register: OUT
      ansible.builtin.debug:
       msg: Hellow to all from play1 task1 {{URL}} {{OUT}}