- name: Play 1
  hosts: all
  vars:
    - URL: websitenew
      
  tasks:
    - name: Run shell command
      shell: uptime
      register: OUT

    - name: Print Message
      ansible.builtin.debug:
       msg: Hellow to all from play1 task1 {{URL}} {{ OUT.stdout }}